/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis.Secretary;
import source.Data;

/**
 *
 * @author cmoore9
 */
public class SecretaryPage extends javax.swing.JFrame {

    /**
     * Creates new form SecretaryPage
     */
    public SecretaryPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientLogOffbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NewPatientbtn = new javax.swing.JButton();
        OrderMedbtn = new javax.swing.JButton();
        RemovePatientbtn = new javax.swing.JButton();
        CreateAppointbtn = new javax.swing.JButton();
        AppointRequstbtn = new javax.swing.JButton();
        RemovalRequestbtn = new javax.swing.JButton();
        PatientLogOffbtn1 = new javax.swing.JButton();

        PatientLogOffbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PatientLogOffbtn.setText("Log off");
        PatientLogOffbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientLogOffbtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Secretary");

        NewPatientbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NewPatientbtn.setText("New Patients");
        NewPatientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPatientbtnActionPerformed(evt);
            }
        });

        OrderMedbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OrderMedbtn.setText("Order Medicine");
        OrderMedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderMedbtnActionPerformed(evt);
            }
        });

        RemovePatientbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RemovePatientbtn.setText("Remove Patients");
        RemovePatientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovePatientbtnActionPerformed(evt);
            }
        });

        CreateAppointbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CreateAppointbtn.setText("Create an Appointment");
        CreateAppointbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAppointbtnActionPerformed(evt);
            }
        });

        AppointRequstbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AppointRequstbtn.setText("Appointment Requests");
        AppointRequstbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AppointRequstbtnActionPerformed(evt);
            }
        });

        RemovalRequestbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RemovalRequestbtn.setText("Removal Requests");
        RemovalRequestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovalRequestbtnActionPerformed(evt);
            }
        });

        PatientLogOffbtn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PatientLogOffbtn1.setText("Log off");
        PatientLogOffbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientLogOffbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PatientLogOffbtn1)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CreateAppointbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AppointRequstbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NewPatientbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(228, 228, 228)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OrderMedbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemovePatientbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemovalRequestbtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(PatientLogOffbtn1))
                    .addComponent(jLabel1))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NewPatientbtn)
                    .addComponent(OrderMedbtn))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AppointRequstbtn)
                    .addComponent(RemovePatientbtn))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateAppointbtn)
                    .addComponent(RemovalRequestbtn))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewPatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPatientbtnActionPerformed
        this.dispose();
        new Sec_NewPatient().setVisible(true);
    }//GEN-LAST:event_NewPatientbtnActionPerformed

    private void AppointRequstbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AppointRequstbtnActionPerformed
        this.dispose();
        new Sec_AppointmentRequests().setVisible(true);
    }//GEN-LAST:event_AppointRequstbtnActionPerformed

    private void CreateAppointbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAppointbtnActionPerformed
        this.dispose();
        new Sec_CreateAppoint().setVisible(true);
    }//GEN-LAST:event_CreateAppointbtnActionPerformed

    private void PatientLogOffbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientLogOffbtnActionPerformed
        Data.setActiveID("");
        this.dispose();
        new guis.MainMenu().setVisible(true);
    }//GEN-LAST:event_PatientLogOffbtnActionPerformed

    private void PatientLogOffbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientLogOffbtn1ActionPerformed
        Data.setActiveID("");
        this.dispose();
        new guis.MainMenu().setVisible(true);
    }//GEN-LAST:event_PatientLogOffbtn1ActionPerformed

    private void OrderMedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderMedbtnActionPerformed
        this.dispose();
        new Sec_OrderMed().setVisible(true);
    }//GEN-LAST:event_OrderMedbtnActionPerformed

    private void RemovePatientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovePatientbtnActionPerformed
        this.dispose();
        new Sec_RemovePatient().setVisible(true);
    }//GEN-LAST:event_RemovePatientbtnActionPerformed

    private void RemovalRequestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovalRequestbtnActionPerformed
        this.dispose();
        new Sec_RemovalRequest().setVisible(true);
    }//GEN-LAST:event_RemovalRequestbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretaryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretaryPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AppointRequstbtn;
    private javax.swing.JButton CreateAppointbtn;
    private javax.swing.JButton NewPatientbtn;
    private javax.swing.JButton OrderMedbtn;
    private javax.swing.JButton PatientLogOffbtn;
    private javax.swing.JButton PatientLogOffbtn1;
    private javax.swing.JButton RemovalRequestbtn;
    private javax.swing.JButton RemovePatientbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
