/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guis.Doctor;
import source.Data;

/**
 *
 * @author cmoore9
 */
public class DoctorPage extends javax.swing.JFrame {

    /**
     * Creates new form DoctorPage
     */
    public DoctorPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DocPatientHisbtn = new javax.swing.JButton();
        DocNewMedbtn = new javax.swing.JButton();
        DocPrescribeMedbtn = new javax.swing.JButton();
        DocAppointmentsbtn = new javax.swing.JButton();
        DocNewAppointbtn = new javax.swing.JButton();
        DocNotesbtn = new javax.swing.JButton();
        PatientLogOffbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Doctor Main Menu");

        DocPatientHisbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DocPatientHisbtn.setText("Patient History");
        DocPatientHisbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocPatientHisbtnActionPerformed(evt);
            }
        });

        DocNewMedbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DocNewMedbtn.setText("New Medicine");
        DocNewMedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocNewMedbtnActionPerformed(evt);
            }
        });

        DocPrescribeMedbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DocPrescribeMedbtn.setText("Prescribe Medicine");
        DocPrescribeMedbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocPrescribeMedbtnActionPerformed(evt);
            }
        });

        DocAppointmentsbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DocAppointmentsbtn.setText("Appointments");
        DocAppointmentsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocAppointmentsbtnActionPerformed(evt);
            }
        });

        DocNewAppointbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DocNewAppointbtn.setText("New Appointment");
        DocNewAppointbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocNewAppointbtnActionPerformed(evt);
            }
        });

        DocNotesbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DocNotesbtn.setText("Notes");
        DocNotesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocNotesbtnActionPerformed(evt);
            }
        });

        PatientLogOffbtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PatientLogOffbtn.setText("Log off");
        PatientLogOffbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientLogOffbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PatientLogOffbtn)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DocPatientHisbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DocAppointmentsbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DocNotesbtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(243, 243, 243)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DocNewAppointbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DocPrescribeMedbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DocNewMedbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PatientLogOffbtn))
                .addGap(114, 114, 114)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocNewAppointbtn)
                    .addComponent(DocAppointmentsbtn))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocPrescribeMedbtn)
                    .addComponent(DocNotesbtn))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DocNewMedbtn)
                    .addComponent(DocPatientHisbtn))
                .addGap(0, 164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocAppointmentsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocAppointmentsbtnActionPerformed
        this.dispose();
        new Doc_ViewAppointment().setVisible(true);
    }//GEN-LAST:event_DocAppointmentsbtnActionPerformed

    private void DocNotesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocNotesbtnActionPerformed
        this.dispose();
        new Doc_Notes().setVisible(true);
    }//GEN-LAST:event_DocNotesbtnActionPerformed

    private void DocPatientHisbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocPatientHisbtnActionPerformed
        this.dispose();
        new Doc_PatientHistory().setVisible(true);
    }//GEN-LAST:event_DocPatientHisbtnActionPerformed

    private void DocNewAppointbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocNewAppointbtnActionPerformed
        this.dispose();
        new Doc_NewAppointment().setVisible(true);
    }//GEN-LAST:event_DocNewAppointbtnActionPerformed

    private void PatientLogOffbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientLogOffbtnActionPerformed
        Data.setActiveID("");
        this.dispose();
        new guis.MainMenu().setVisible(true);
    }//GEN-LAST:event_PatientLogOffbtnActionPerformed

    private void DocPrescribeMedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocPrescribeMedbtnActionPerformed
        this.dispose();
        new Doc_PrescribeMed().setVisible(true);
    }//GEN-LAST:event_DocPrescribeMedbtnActionPerformed

    private void DocNewMedbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocNewMedbtnActionPerformed
        this.dispose();
        new Doc_NewMed().setVisible(true);
    }//GEN-LAST:event_DocNewMedbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DocAppointmentsbtn;
    private javax.swing.JButton DocNewAppointbtn;
    private javax.swing.JButton DocNewMedbtn;
    private javax.swing.JButton DocNotesbtn;
    private javax.swing.JButton DocPatientHisbtn;
    private javax.swing.JButton DocPrescribeMedbtn;
    private javax.swing.JButton PatientLogOffbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
